# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0006_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminars',
            name='event_price_person',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
