# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0007_seminars_event_price_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminars',
            name='event_price_person',
            field=models.CharField(blank=True, default=b'', max_length=1000, null=True),
        ),
    ]
