# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0009_seminars_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminars',
            name='event_urgent_info',
            field=models.CharField(blank=True, default=b'', max_length=1000, null=True),
        ),
    ]
