# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0010_seminars_event_urgent_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Тендер: Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Тендер: Города'},
        ),
        migrations.AlterModelOptions(
            name='fzs',
            options={'verbose_name_plural': 'Тендер: Федеральные законы'},
        ),
        migrations.AlterModelOptions(
            name='seminar_programs',
            options={'verbose_name_plural': 'Тендер: Программы семинаров'},
        ),
        migrations.AlterModelOptions(
            name='seminars',
            options={'verbose_name_plural': 'Тендер: Семинары'},
        ),
        migrations.AlterField(
            model_name='banners',
            name='last_click',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last click date/time'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='picture',
            field=models.FileField(upload_to='city_pictures/'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='posted',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='seminar_programs',
            name='program_file',
            field=models.FileField(blank=True, null=True, upload_to='seminar_programs/'),
        ),
        migrations.AlterField(
            model_name='seminars',
            name='event_date',
            field=models.DateTimeField(verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='seminars',
            name='event_price_person',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seminars',
            name='event_title',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seminars',
            name='event_urgent_info',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
