# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0012_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fzs',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
