# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0013_auto_20160830_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('seminar_types', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Сайт: Подписки на рассылки',
            },
        ),
        migrations.AddField(
            model_name='fzs',
            name='allow_subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
