# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0014_auto_20160905_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='fzs',
            name='short_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
