# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0016_auto_20160905_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='city',
            new_name='region',
        ),
    ]
