# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0021_auto_20161011_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminars',
            name='event_place',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
