# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0022_seminars_event_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('promocode', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Сайт: Промокоды',
            },
        ),
    ]
