# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0024_auto_20170127_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='fzs',
            name='mini_top_desc',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
