# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0025_fzs_mini_top_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminars',
            name='event_is_webinar',
            field=models.BooleanField(default=False),
        ),
    ]
