# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0026_seminars_event_is_webinar'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminars',
            name='event_primary_mini',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seminars',
            name='event_primary_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
